source 'https://github.com.cnpmjs.org/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'KTVGrab_Example' do
    pod 'KTVGrab', :path => '../'
    pod 'ZegoLyricView', :git => 'https://github.com/zegoim/ZegoLyricView-iOS.git', :branch => 'master'
    pod 'ZegoPitchView', :git => 'https://github.com/zegoim/ZegoPitchView-iOS.git', :branch => 'master'
    pod 'GoKit', :git => 'https://github.com/zegoim/ZegoGoKit-iOS.git', :branch => 'master'
    pod 'ZegoNetwork', :git => 'https://github.com/zegoim/ZegoGoNetwork-iOS.git', :branch => 'master'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

end
